# Todo: May be can auto discovery
upstream http_server {
  ip_hash;
  server web:8080;  # this is reachable from inside the container network; external access is on port 80
}

server {
  listen 80;
  # listen [::]:80;
  # server_name demo.example.com;  # uncomment and change to your own domain
  return 307 https://$host$request_uri;
}

server {
  listen 443 ssl;
  http2 on;
  # listen [::]:443 ssl;
  # server_name demo.example.com;      # uncomment and change to your own domain
  server_tokens off;
  ssl_certificate cert/server.crt;        # replace server.crt with your certificate, keep the certs/ path unchanged
  ssl_certificate_key cert/server.key;    # replace server.key with your certificate, keep the certs/ path unchanged
  ssl_session_timeout 1d;
  ssl_session_cache shared:MozSSL:10m;
  ssl_session_tickets off;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
  ssl_prefer_server_ciphers off;

  client_max_body_size 5000m;

  location / {
    proxy_pass http://http_server;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_set_header X-Forwarded-For $remote_addr;
    # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # if there is another SLB upstream, use $proxy_add_x_forwarded_for to get the real IP

    proxy_ignore_client_abort on;
    proxy_connect_timeout 600;
    proxy_send_timeout 600;
    proxy_read_timeout 600;
    send_timeout 6000;
  }
}