on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release And Upload assets

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          TAG=$(basename ${GITHUB_REF})
          REPO_NAME=$(basename ${GITHUB_REPOSITORY})
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-config.yml
          version: ${{ steps.get_version.outputs.TAG }}
          tag: ${{ steps.get_version.outputs.TAG }}
      
      - name: Create Upload Assets
        run: |
          NAME="${{ steps.get_version.outputs.REPO_NAME }}-${{ steps.get_version.outputs.TAG }}"
          mkdir -p build "$NAME"
          git archive --format tar HEAD | tar x -C "$NAME"
          sed -i "s@^export VERSION=.*@export VERSION=${{ steps.get_version.outputs.TAG }}@" "$NAME/static.env"
          tar -czf "build/${NAME}.tar.gz" "$NAME"
          cd build
          md5sum "${NAME}.tar.gz" > "${NAME}.tar.gz.md5"
          
      - name: Release Upload Assets
        run: |
          gh release upload ${{ steps.get_version.outputs.TAG }} build/* -R $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}